### ISSUE TITLE
Edit/update support for ComponentSchematics.

### ISSUE THREAD

**Issue by jiria** [oam-dev/rudr#178]
Hello,

This is based on last week experiments. When I tried to kubectl edit configuration or just reapply the configuration yaml, the changes were not applied. Also, I believe I saw a message from the Scylla pod about updates not being supported. So wanted to check if that is the case and if there is an ETA for edit/update support.

**Comment by technosophos** [comment]
The intention was that components would be static and immutable. Each time a component is changed, a new "version" of that should be created. As of this writing, the way we are managing component versions is to add the version string to the end of the `metadata.name` in Kubernetes, e.g. `foo-v3`. This is because (a) there is currently not a better way to reference components, and (b) Kubernetes doesn't really have a built-in definition of _version_. I think we want to do something better in the future. But for now, this particular bug is probably a `wontfix`.
