### ISSUE TITLE
Add example how OAM could corporate with Kustomize/Helm to manage complicated parameters

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/rudr#379]
Now OAM use parameters/variables/properties which could be very long and complicated, we should use tools such like kustomize or helm template to solve this.

Maybe we could add some examples.

/cc @hongchaodeng @resouer

**Comment by xiang90** [comment]
Yep. I think this example can also further clarify the relationship between kustomize/helm and OAM. We REALLY need to show they intend to solve very different set of problems based on the feedback from our initial release.

**Comment by resouer** [comment]
We will include examples of using parametering tool (helm, kustomize etc) instead of `fromParam` as well (will need an admission hook in this case https://github.com/oam-dev/rudr/issues/349).

The goal is to clarify plain YAML + external tools is totally supported with OAM without any syntax sugar like `fromParam`. Also, it will help to prove the sugar is actually sweet :-)
