### ISSUE TITLE
componentName and trait type impl VS OAM spec

### ISSUE THREAD

**Issue by AdrienFromToulouse** [oam-dev/rudr#392]
Hi!

I did give a try to `rudr`. That is very neat 👍 all just works!

However by digging a bit more around OAM and the `rudr` implementation of it, I have a couple of interrogations. 

In regards to `ApplicationConfiguration`.

I can see in the spec that for instance `trait` have to have a type and `components` a `componentName`. because rudr is of course for k8s then it is implemented as `name` rather than `componentName`. Also traits don't have a type.

I know it is still work in progress, however I was if tools that implement OAM should be checking the incoming `ApplicationConfiguration` as being compliant with the spec. If not, a such `ApplicationConfiguration` is not fully portable to another "runtime".

Did I understood well the OAM philosophy and more so the `rudr` implementation?

Cheers!

References:

https://github.com/oam-dev/spec/blob/master/schema/application_configuration.schema.json#L157

https://github.com/oam-dev/spec/blob/master/schema/application_configuration.schema.json#L190

**Comment by macolso** [comment]
You definitely have a good handle on the OAM philosophy and ```rudr``` implementation. We've thought of creating some sort of OAM implementation compliance tool but don't currently have anything in the works. 
1st link - I'm not sure if we have plans to rename ```rudr```'s field from```name``` to ```componentName```. @technosophos can speak to that.  
2nd link - Good catch! That looks like a piece of the OAM documentation that needs to be cleaned up. We used to have the concept of a ```trait``` type but eventually decided against it since traits are a runtime behavior and not an instantiated object (making name and type fields redundant). All implementations of OAM should include a field for ```trait``` name but not ```trait``` type.

**Comment by vturecek** [comment]
Well, rudr will have to conform to whatever is in the spec. Rudr might just be a little behind on some of the minor changes we made to field names in the spec. 

The spec schema needs to be fixed though, good catch there. Validation tools will rely on the schema being correct, so we need to be diligent about keeping that consistent with the definitions in the rest of the spec.

**Comment by wonderflow** [comment]
I will align `components.name` to  `components.componentName`.
