### ISSUE TITLE
Ingress example has incorrect port name in the componentspec

### ISSUE THREAD

**Issue by iyyappam** [oam-dev/rudr#425]
Should the port name be service_port which is used in the configuration instead of http?

https://github.com/oam-dev/rudr/blob/master/docs/concepts/traits.md

apiVersion: core.oam.dev/v1alpha1
kind: ComponentSchematic
metadata:
  name: nginx-replicated-v1
spec:
  workloadType: core.oam.dev/v1alpha1.Server
  containers:
  - image: nginx:latest
    name: server
    ports:
    - containerPort: 80                  # <-- this is the service port
      name: http                            # -------> servivce_port?
      protocol: TCP

**Comment by wonderflow** [comment]
Not like that, They have different meanings.

Port name in component here, represents the port usage, while service_port is a parameter of ingress trait which represent the port ingress will bind with.

App Developer don't need to specify which ingress they want to bind , because they don't care.
On the other side, App Operator should concern which port they are going to bind with ingress, so they using service_port to specify.

**Comment by suhuruli** [comment]
@iyyappam , does @wonderflow's comment make sense? Do you think we should have better names for these properties?

**Comment by iyyappam** [comment]
I understand they have a different meaning, but my point is to make the naming simpler to understand how the mapping is done. Or you can add a comment indicating how the container port is mapped to ingress port.

**Comment by wonderflow** [comment]
I'm not sure if this doc can help you understand: https://github.com/oam-dev/rudr/blob/master/docs/concepts/traits.md#properties-2

mapping is done by the appconfig

> Because each component may have multiple ports, the specific port must be defined in the ApplicationConfiguration

**Comment by wonderflow** [comment]
@iyyappam  I'm not sure if we could close this issue? Feel free to tell us if there was any confusing.

**Comment by iyyappam** [comment]
We can close it.
