### ISSUE TITLE
Log message is confusing: "skip update status for {appConfig} find the spec has changes to be execute"

### ISSUE THREAD

**Issue by MikkelHegn** [oam-dev/rudr#493]
**Describe the bug**
We see this log message in rudr: "skip update status for {appConfig} find the spec has changes to be execute". It's not clear if there are changes to be executed or not, as it states 'skip' but also 'has changes to be executed'

**What happened**:
Applied an updated application configuration

**What you expected to happen**:
A clear log message telling me whether the specification had changed and that action will be taken.

**Comment by wonderflow** [comment]
There are two execution loops to reconcile the changes of AppConfig. One is the main control loop, another is the status check loop.
This message shows the status check loop can't change the status of AppConfig because the main control loop haven't finished reconcile it.

Advices to make it more clear are welcome.

**Comment by MikkelHegn** [comment]
A few thing that might help:
1. Add the source as part of the message: "MainControlLoop: {logMessage}" and "CheckControlLoop: {logMessage}
2. Make the text more verbose in terms of what action is taken and what's not, and the cause (if known).

What's interesting about this, is that I did not see any logs telling me the Main loop updated the status.
